# 1) Ignoring this allows us to continue to update pyOpenSSL (one of our crypto
#    dependencies) until https://github.com/certbot/certbot/issues/9828 is resolved.
filterwarnings =
    error
    ignore:X509Extension support in pyOpenSSL is deprecated:DeprecationWarning
