FROM python:3.8-slim as base

# When building locally, these should be set to your UID/GID.  That way, any
# files written to the $PWD mount will be owned by you.  This is not
# necessary (or wanted) when building in Concourse.
ARG UID=2000
ARG GID=2000
ARG USER=app

RUN grep -q ":$GID:" /etc/group || groupadd --gid=$GID $USER
RUN useradd \
      --home-dir=/home/$USER \
      --no-log-init \
      --create-home \
      --shell=/bin/bash \
      --gid=$GID \
      --uid=$UID \
      --no-user-group \
      --non-unique \
      $USER

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      sqlite3 \
      libsqlite3-dev \
      build-essential \
      libpq-dev \
      procps \
      git

# Install Fake Pebble LE server
COPY --from=letsencrypt/pebble /usr/bin/pebble /usr/bin/pebble
COPY --from=letsencrypt/pebble /test/ /test/
COPY --from=letsencrypt/pebble-challtestsrv /usr/bin/pebble-challtestsrv /usr/bin/pebble-challtestsrv

# Install Redis
# cloud.gov currently supports redis 3.2
COPY --from=redis:3.2 /usr/local/bin/redis-server /usr/bin/redis-server
COPY --from=redis:3.2 /usr/local/bin/redis-cli /usr/bin/redis-cli

RUN cp /test/certs/pebble.minica.pem /usr/local/share/ca-certificates/pebble.crt
RUN update-ca-certificates

RUN pip install --upgrade pip
COPY pip-tools/dev-requirements.txt ./pip-tools/
RUN pip install -r pip-tools/dev-requirements.txt

WORKDIR /app
RUN chown "$UID:$GID" .
USER $UID:$GID

COPY . .

ENV PATH=/usr/local/bin:$PATH
ENV FLASK_APP="broker:create_app()"
ENV FLASK_ENV=local-development
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["/app/docker/entrypoint.sh"]
CMD ["bash"]

