#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -x

# Concourse politely ignores our ENTRYPOINT. :shrug:"
/app/docker/start-redis.sh

export FLASK_ENV=test

if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  shift
  ptw -- -v "$@"
else
  python -m pytest -v "$@"
fi

/app/docker/stop-redis.sh
