#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -x

export FLASK_ENV=test

if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  ptw -- -v
else
  eval python -m pytest -v
fi
