#!/usr/bin/env bash

# Used to run the app and the worker from within Docker

set -euo pipefail
shopt -s inherit_errexit

cd "$(dirname "$0")/.."

flask db upgrade

docker/start-redis.sh &
scripts/run-app &
scripts/run-worker &

wait
