#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -xeuo pipefail

./docker/start-servers.sh

export FLASK_ENV=test
env | sort

ls -lA

echo -n "Python sys.path: "
python3 -c 'import sys; print(sys.path)'

if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  shift
  ptw --spool=500 -n -c -w -- -Werror -vv "$@"
else
  python -m pytest -Werror -vv "$@"
fi

./docker/stop-servers.sh
