#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -xeuo pipefail

./docker/start-servers.sh

export FLASK_ENV=test

if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  shift
  ptw . --now --clear --delay 0.2 -- -Werror -vv "$@"
else
  python -m pytest -Werror -vv "$@"
fi

./docker/stop-servers.sh
