#!/usr/bin/env bash

cd /app || (echo "Cannot find /app directory"; exit 2)
set -xeuo pipefail

./docker/start-servers.sh

export FLASK_ENV=test

if [[ "$#" -ge 1 ]] && [[ "$1" == "watch" ]]; then
  shift
  ptw .
else
  python3.11 -m pytest "$@"
fi

./docker/stop-servers.sh
