"""CdnServiceInstance as a subclass of ServiceInstance

Revision ID: 046fd7fac9f8
Revises: 8cb1ecea6207
Create Date: 2020-06-10 22:20:19.144509

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "046fd7fac9f8"
down_revision = "8cb1ecea6207"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_instance", sa.Column("instance_type", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_instance", "instance_type")
    # ### end Alembic commands ###
