"""Add alb_certificate column to MigrateDedicatedALBToCDNDedicatedWafServiceInstance

Revision ID: 06eae5d555f0
Revises: f411b8287906
Create Date: 2025-05-27 14:47:52.707526

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06eae5d555f0"
down_revision = "f411b8287906"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("alb_certificate_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk__service_instance__certificate__alb_certificate_id",
            "certificate",
            ["alb_certificate_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk__service_instance__certificate__alb_certificate_id", type_="foreignkey"
        )
        batch_op.drop_column("alb_certificate_id")

    # ### end Alembic commands ###
