"""Add fullchain_pem to ServiceInstance

Revision ID: 12607233c729
Revises: 60d6c9761d15
Create Date: 2020-05-20 16:11:50.304351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12607233c729"
down_revision = "60d6c9761d15"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fullchain_pem", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("fullchain_pem")

    # ### end Alembic commands ###
