"""add instance_type to DedicatedALB model

Revision ID: 207ac132731a
Revises: def670fc0f33
Create Date: 2025-07-08 21:10:52.017088

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "207ac132731a"
down_revision = "def670fc0f33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.add_column(sa.Column("instance_type", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.drop_column("instance_type")

    # ### end Alembic commands ###
