"""create dedicated_alb model

Revision ID: 362f5002f35e
Revises: 06eae5d555f0
Create Date: 2025-07-08 15:09:48.930561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "362f5002f35e"
down_revision = "06eae5d555f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedicated_alb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alb_arn", sa.String(), nullable=False),
        sa.Column("dedicated_org", sa.String(), nullable=True),
        sa.Column("dedicated_waf_web_acl_arn", sa.String(), nullable=True),
        sa.Column("dedicated_waf_web_acl_id", sa.String(), nullable=True),
        sa.Column("dedicated_waf_web_acl_name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alb_arn"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dedicated_alb")
    # ### end Alembic commands ###
