"""add route53 change ids to service instance

Revision ID: 379cd16f1ba5
Revises: 1ebd34d71844
Create Date: 2020-05-29 02:12:48.598731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "379cd16f1ba5"
down_revision = "1ebd34d71844"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("route53_change_ids", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("route53_change_ids")

    # ### end Alembic commands ###
