"""add cloudwatch_health_check_alarm_arns

Revision ID: 38b7e9da2fb9
Revises: 819e31a29986
Create Date: 2024-09-03 20:12:26.380305

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "38b7e9da2fb9"
down_revision = "819e31a29986"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "cloudwatch_health_check_alarm_arns",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("cloudwatch_health_check_alarm_arns")

    # ### end Alembic commands ###
