"""share domain_internal, rename alb_id to alb_arn

Revision ID: 45288546dc63
Revises: 73f17eb26721
Create Date: 2020-06-16 23:02:51.378117

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "45288546dc63"
down_revision = "73f17eb26721"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_instance", sa.Column("alb_arn", sa.String(), nullable=True))
    op.add_column(
        "service_instance", sa.Column("domain_internal", sa.String(), nullable=True)
    )
    op.drop_column("service_instance", "alb_id")
    op.drop_column("service_instance", "cloudfront_distribution_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_instance",
        sa.Column(
            "cloudfront_distribution_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "service_instance",
        sa.Column("alb_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("service_instance", "domain_internal")
    op.drop_column("service_instance", "alb_arn")
    # ### end Alembic commands ###
