"""add_sns_notification_topic_arn

Revision ID: 5afacdbeec29
Revises: 9919681623cc
Create Date: 2024-09-18 20:35:48.398374

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5afacdbeec29"
down_revision = "9919681623cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sns_notification_topic_arn", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("sns_notification_topic_arn")

    # ### end Alembic commands ###
