"""Add challenge table

Revision ID: 60d6c9761d15
Revises: c8145751f808
Create Date: 2020-05-08 18:13:50.972882

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60d6c9761d15"
down_revision = "c8145751f808"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenge",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_instance_id", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("validation_domain", sa.String(), nullable=False),
        sa.Column("validation_contents", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["service_instance_id"], ["service_instance.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("challenge")
    # ### end Alembic commands ###
