"""add cookie settings

Revision ID: 68727f5db74e
Revises: f16a5133b6ea
Create Date: 2020-06-29 21:01:11.614635

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "68727f5db74e"
down_revision = "f16a5133b6ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_instance",
        sa.Column("forward_cookie_policy", sa.String(), nullable=True),
    )
    op.add_column(
        "service_instance",
        sa.Column(
            "forwarded_cookies", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_instance", "forwarded_cookies")
    op.drop_column("service_instance", "forward_cookie_policy")
    # ### end Alembic commands ###
