"""add custom error config

Revision ID: 6a67c708208f
Revises: ad4dff9923c0
Create Date: 2020-08-11 16:57:36.626822

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6a67c708208f"
down_revision = "ad4dff9923c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_instance",
        sa.Column(
            "error_responses", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_instance", "error_responses")
    # ### end Alembic commands ###
