"""add dedicated_waf_associated

Revision ID: 6ee28f67bcc0
Revises: 207ac132731a
Create Date: 2025-07-17 15:45:15.027303

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6ee28f67bcc0"
down_revision = "207ac132731a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("dedicated_waf_associated", sa.Boolean(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.drop_column("dedicated_waf_associated")

    # ### end Alembic commands ###
