"""add iam certificate arn to service instance

Revision ID: 73414dbba59b
Revises: e2dc1ebb575a
Create Date: 2020-05-22 22:49:57.270586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73414dbba59b"
down_revision = "e2dc1ebb575a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("iam_server_certificate_arn", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("iam_server_certificate_arn")
