"""Add ALBServiceInstance

Revision ID: 73f17eb26721
Revises: 046fd7fac9f8
Create Date: 2020-06-16 19:13:49.523667

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "73f17eb26721"
down_revision = "046fd7fac9f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("service_instance", sa.Column("alb_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_instance", "alb_id")
    # ### end Alembic commands ###
