"""add tags column to DedicatedALB model

Revision ID: 77a0dfc0552d
Revises: 6ee28f67bcc0
Create Date: 2025-07-17 19:03:56.954737

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77a0dfc0552d"
down_revision = "6ee28f67bcc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
