"""add canceled_at for operations

Revision ID: 7b5e889e7328
Revises: b671b2b52afb
Create Date: 2020-06-19 23:33:37.838852

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "7b5e889e7328"
down_revision = "b671b2b52afb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation",
        sa.Column("canceled_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "canceled_at")
    # ### end Alembic commands ###
