"""add tags column

Revision ID: 7ddef9f2b7a6
Revises: 8bfa2dd3a367
Create Date: 2024-07-05 18:48:55.778958

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7ddef9f2b7a6"
down_revision = "8bfa2dd3a367"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
