"""add action to operation

Revision ID: 8851c1a5ebaa
Revises: 049d8428df01
Create Date: 2020-05-31 21:31:32.201381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8851c1a5ebaa"
down_revision = "049d8428df01"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("operation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "action",
                sa.Enum("Provision", "Deprovision", name="actions"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("operation", schema=None) as batch_op:
        batch_op.drop_column("action")

    # ### end Alembic commands ###
