"""add CDN dedicated WAF ACL columns

Revision ID: 8bfa2dd3a367
Revises: c20d84a94456
Create Date: 2024-07-02 21:53:25.804274

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bfa2dd3a367"
down_revision = "c20d84a94456"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("dedicated_waf_web_acl_id", sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("dedicated_waf_web_acl_name", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("dedicated_waf_web_acl_name")
        batch_op.drop_column("dedicated_waf_web_acl_id")

    # ### end Alembic commands ###
