"""Add DedicatedALBServiceInstance and DedicatedALBListener

Revision ID: 9a192af8c4ae
Revises: 6a67c708208f
Create Date: 2024-03-20 01:15:41.335973

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "9a192af8c4ae"
down_revision = "6a67c708208f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedicated_alb_listener",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listener_arn", sa.String(), nullable=False),
        sa.Column("alb_arn", sa.String(), nullable=True),
        sa.Column("dedicated_org", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listener_arn"),
    )
    op.add_column("service_instance", sa.Column("org_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_instance", "org_id")
    op.drop_table("dedicated_alb_listener")
    # ### end Alembic commands ###
