"""Add domain private key to service instance

Revision ID: 9a27d9bdc5a7
Revises: ea0cd34d6a9e
Create Date: 2020-05-07 20:36:36.458440

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a27d9bdc5a7"
down_revision = "ea0cd34d6a9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("csr_pem", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("private_key_pem", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("private_key_pem")
        batch_op.drop_column("csr_pem")

    # ### end Alembic commands ###
