"""make alb_arn non-nullable

Revision ID: a4sfwv8s5meh
Revises: 362f5002f35e
Create Date: 2025-07-08 15:10:48.930561

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4sfwv8s5meh"
down_revision = "362f5002f35e"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("dedicated_alb_listener", schema=None) as batch_op:
        batch_op.alter_column("alb_arn", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb_listener", schema=None) as batch_op:
        batch_op.alter_column("alb_arn", existing_type=sa.VARCHAR(), nullable=True)
