"""previous listener data for ALB

Revision ID: ad4dff9923c0
Revises: be40fe7b6ecb
Create Date: 2020-08-03 17:57:14.855615

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "ad4dff9923c0"
down_revision = "be40fe7b6ecb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_instance", sa.Column("previous_alb_arn", sa.String(), nullable=True)
    )
    op.add_column(
        "service_instance",
        sa.Column("previous_alb_listener_arn", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service_instance", "previous_alb_listener_arn")
    op.drop_column("service_instance", "previous_alb_arn")
    # ### end Alembic commands ###
