"""Add domains to service instances

Revision ID: c8145751f808
Revises: 9a27d9bdc5a7
Create Date: 2020-05-07 22:30:55.818722

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8145751f808"
down_revision = "9a27d9bdc5a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("domain_names", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("domain_names")

    # ### end Alembic commands ###
