"""add origin information to service instance

Revision ID: cbb0b5789fa6
Revises: d5aa5942fade
Create Date: 2020-05-30 22:09:09.713581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb0b5789fa6'
down_revision = 'd5aa5942fade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudfront_origin_hostname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cloudfront_origin_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_instance', schema=None) as batch_op:
        batch_op.drop_column('cloudfront_origin_path')
        batch_op.drop_column('cloudfront_origin_hostname')

    # ### end Alembic commands ###
