"""add_alarm_notification_email

Revision ID: cc7720fac6d9
Revises: 4c57fe392f3c
Create Date: 2024-09-17 22:20:32.297690

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc7720fac6d9"
down_revision = "4c57fe392f3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("alarm_notification_email", sa.String(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("alarm_notification_email")

    # ### end Alembic commands ###
