"""make dedicated_org non-nullable

Revision ID: def670fc0f33
Revises: a4sfwv8s5meh
Create Date: 2025-07-08 16:01:47.593488

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "def670fc0f33"
down_revision = "a4sfwv8s5meh"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.alter_column(
            "dedicated_org", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("dedicated_alb_listener", schema=None) as batch_op:
        batch_op.alter_column(
            "dedicated_org", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedicated_alb_listener", schema=None) as batch_op:
        batch_op.alter_column(
            "dedicated_org", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("dedicated_alb", schema=None) as batch_op:
        batch_op.alter_column(
            "dedicated_org", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
