"""add cert_pem to service instance

Revision ID: e2dc1ebb575a
Revises: c7e592108471
Create Date: 2020-05-22 18:21:30.205015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2dc1ebb575a"
down_revision = "c7e592108471"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cert_pem", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("cert_pem")

    # ### end Alembic commands ###
