"""Add order_json to ServiceInstance

Revision ID: e4e202fc7541
Revises: 7544ec0f0572
Create Date: 2020-05-20 18:17:55.248123

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e4e202fc7541"
down_revision = "7544ec0f0572"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_json", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("order_json")

    # ### end Alembic commands ###
