"""add_ddos_detected_cloudwatch_alarm_name

Revision ID: e56aab1c13c0
Revises: 5afacdbeec29
Create Date: 2024-09-18 21:17:32.095791

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e56aab1c13c0"
down_revision = "5afacdbeec29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ddos_detected_cloudwatch_alarm_name", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("ddos_detected_cloudwatch_alarm_name")

    # ### end Alembic commands ###
