"""Add ACMEUser model

Revision ID: ea0cd34d6a9e
Revises: 120d4ff72a67
Create Date: 2020-05-04 15:46:40.791304

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea0cd34d6a9e"
down_revision = "120d4ff72a67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acme_user",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("uri", sa.String(), nullable=False),
        sa.Column("private_key_pem", sa.Text(), nullable=False),
        sa.Column("registration_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(sa.Column("acme_user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "acme_user_id", "acme_user", ["acme_user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_constraint("acme_user_id", type_="foreignkey")
        batch_op.drop_column("acme_user_id")

    op.drop_table("acme_user")
    # ### end Alembic commands ###
