"""Add iam server cert name to service instance

Revision ID: f7a62bb144e3
Revises: 9876ac4778c2
Create Date: 2020-06-02 21:16:48.136860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a62bb144e3'
down_revision = '9876ac4778c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iam_server_certificate_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_instance', schema=None) as batch_op:
        batch_op.drop_column('iam_server_certificate_name')

    # ### end Alembic commands ###
