"""add cloudfront arn to service instance

Revision ID: f9d6018a855d
Revises: 73414dbba59b
Create Date: 2020-05-27 19:45:54.359050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9d6018a855d"
down_revision = "73414dbba59b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cloudfront_distribution_arn", sa.String(), nullable=True)
        )

        batch_op.add_column(
            sa.Column("cloudfront_distribution_id", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("cloudfront_distribution_arn")
        batch_op.drop_column("cloudfront_distribution_id")
