"""add deactivatted at to service instance

Revision ID: fd182d3d1873
Revises: f7a62bb144e3
Create Date: 2020-06-02 22:40:51.347149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd182d3d1873"
down_revision = "f7a62bb144e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deactivated_at", sa.TIMESTAMP(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("service_instance", schema=None) as batch_op:
        batch_op.drop_column("deactivated_at")

    # ### end Alembic commands ###
