#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

export PYTHONPATH=$(dirname "$0")/..

opts=""

if [[ ! ${INSTANCE_INDEX:-0} = 0 ]]; then
    opts="$opts --no-periodic"
fi

# send logs to dev null, since we create other log handlers elsewhere
exec huey_consumer.py "$@" $opts broker.huey_consumer.huey -l /dev/null 
