#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

export PYTHONPATH=$(dirname "$0")/..

# send logs to dev null, since we create other log handlers elsewhere
exec huey_consumer.py "$@" broker.huey_consumer.huey -l /dev/null
