#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

main() {
  if [[ $# -eq 0 ]]; then
    command=once
  else
    command="$1"
    shift
  fi

  cd "$(dirname "$0")/.."

  case $command in
    -h)
      usage
      ;;
    once)
      run_tests "$@"
      ;;
    watch)
      watch_tests "$@"
      ;;
    run)
      run "$@"
      ;;
    shell)
      shell
      ;;
    *)
      usage "Unknown command: $command"
      ;;
  esac
}

build_image_and_return_id() {
  docker build -q -f docker/Dockerfile --target=dev .
}

run_docker() {
  docker run -it -v "$PWD:/app" --tmpfs=/db "$@"
}

run_tests() {
  id=$(build_image_and_return_id)
  run_docker "$id" docker/run_tests "$@"
}

watch_tests() {
  id=$(build_image_and_return_id)
  run_docker "$id" ptw -cw "$@"
}

run() {
  id=$(build_image_and_return_id)
  run_docker "$id" "$@"
}

shell() {
  id=$(build_image_and_return_id)
  run_docker "$id" "bash"
}

usage() {
  [[ $# -gt 0 ]] && echo "ERROR: $*"
  local me=$(basename "$0")
  cat <<-EOF

  USAGE: $me [watch|once|run|shell]

  Runs the tests

  Examples:

  $me           # Runs the tests once
  $me once      # Same as above
  $me watch     # Continually watches for file changes and runs tests
  $me shell     # Gives an interactive bash shell in the tests container
  $me run foo   # Runs 'foo' in the test container
	EOF
  exit 1
}

main "$@"
