#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

main() {
  if [[ $# -eq 0 ]]; then
    command=once
  else
    command="$1"
    shift
  fi

  cd "$(dirname "$0")/.."

  case $command in
    once)
      run_tests
      ;;
    watch)
      watch_tests
      ;;
    shell)
      shell
      ;;
    *)
      usage "Unknown command: $command"
      ;;
  esac
}

build_image_and_return_id() {
  docker build -q -f docker/Dockerfile --target=dev .
}

run_docker() {
  docker run -it -v "$PWD:/app" "$@"
}

run_tests() {
  id=$(build_image_and_return_id)
  run_docker "$id" "docker/run_tests"
}

watch_tests() {
  id=$(build_image_and_return_id)
  run_docker "$id" "ptw"
}

shell() {
  id=$(build_image_and_return_id)
  run_docker "$id" "bash"
}

usage() {
  [[ $# -gt 0 ]] && echo "ERROR: $*"
  local me=$(basename "$0")
  cat <<-EOF

  USAGE: $me [watch|once|shell]

  Runs the test (and maybe watches them)
	EOF
  exit 1
}

main "$@"
