#!/usr/bin/env bash

set -euo pipefail

export UID=$(id -u)
export GID=$(id -g)
export USER

cd "$(git rev-parse --show-toplevel)"

# We create the dockerfile inline to ensure that the files written to the
# mounted volume (which is our local directory) are written with our ids.
export DOCKERFILE=$(cat <<EOD
FROM python:3.8
RUN pip install --upgrade pip && \
    pip install --no-cache-dir pip-tools
RUN groupadd --gid=$GID $USER
RUN useradd \
      --home-dir=/home/$USER \
      --no-log-init \
      --create-home \
      --shell=/bin/bash \
      --gid=$GID \
      --uid=$UID \
      $USER

USER $USER:$USER

WORKDIR /app

ENV CUSTOM_COMPILE_COMMAND="$0"
EOD
)

echo "Building the temporary docker image"
id=$(echo "$DOCKERFILE" | docker build -f - -q .)

echo "Compiling requirements.txt"
docker run -v "$PWD:/app" "$id" \
  pip-compile \
  --quiet \
  --output-file=requirements.txt \
  pip-tools/requirements.in

echo "Compiling dev-requirements.txt"
docker run -v "$PWD:/app" "$id" \
  pip-compile \
  --quiet \
  --output-file=dev-requirements.txt \
  pip-tools/dev-requirements.in
