############################
#  SHARED

broker-register-params: &broker-register-params
  CF_ORGANIZATION: ((broker-organization))
  CF_SPACE: ((broker-space))
  BROKER_NAME: ((name))
  AUTH_USER: ((broker-auth-username))
  AUTH_PASS: ((broker-auth-password))
  SERVICES: ((service-name))

cf-creds-dev: &cf-creds-dev
  CF_API_URL: ((dev-cf-api-url))
  CF_USERNAME: ((dev-cf-username))
  CF_PASSWORD: ((dev-cf-password))
  CF_ORGANIZATION: ((broker-organization))
  CF_SPACE: ((broker-space))

cf-creds-staging: &cf-creds-staging
  CF_API_URL: ((staging-cf-api-url))
  CF_USERNAME: ((staging-cf-username))
  CF_PASSWORD: ((staging-cf-password))
  CF_ORGANIZATION: ((broker-organization))
  CF_SPACE: ((broker-space))

cf-creds-production: &cf-creds-production
  CF_API_URL: ((production-cf-api-url))
  CF_USERNAME: ((production-cf-username))
  CF_PASSWORD: ((production-cf-password))
  CF_ORGANIZATION: ((broker-organization))
  CF_SPACE: ((broker-space))

create-postgres-service-params: &create-postgres-service-params
  APP_NAME: ((name))
  SVC_SERVICE: ((db_service))
  SVC_PLAN: ((db_plan))
  SVC_NAME: ((db_name))

create-redis-service-params: &create-redis-service-params
  APP_NAME: ((name))
  SVC_SERVICE: ((redis_service))
  SVC_PLAN: ((redis_plan))
  SVC_NAME: ((redis_name))

upgrade-schema-vars: &upgrade-schema-vars
  FLASK_ENV: upgrade-schema
  APP_NAME: ((name))-db-upgrade
  DB_NAME: ((db_name))
  REDIS_NAME: ((redis_name))

cf-manifest-vars: &cf-manifest-vars
  vars:
    APP_NAME: ((name))
    DB_NAME: ((db_name))
    REDIS_NAME: ((redis_name))

cf-manifest-env-dev: &cf-manifest-env-dev
  environment_variables:
    FLASK_ENV: development
    BROKER_USERNAME: ((broker-auth-username))
    BROKER_PASSWORD: ((broker-auth-password))
    SECRET_KEY: ((flask-secret-key))
    DATABASE_ENCRYPTION_KEY: ((dev-db-encryption-key))
    ROUTE53_ZONE_ID: ((dev-route53-zone-id))
    DNS_ROOT_DOMAIN: ((dev-dns-root-domain))
    DEFAULT_CLOUDFRONT_ORIGIN: ((dev-default-cloudfront-origin-domain-name))
    AWS_GOVCLOUD_REGION: ((dev-aws-govcloud-region))
    AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((dev-aws-govcloud-secret-access-key))
    AWS_GOVCLOUD_ACCESS_KEY_ID: ((dev-aws-govcloud-access-key-id))
    AWS_COMMERCIAL_REGION: ((dev-aws-commercial-region))
    AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((dev-aws-commercial-secret-access-key))
    AWS_COMMERCIAL_ACCESS_KEY_ID: ((dev-aws-commercial-access-key-id))
    ALB_LISTENER_ARNS: ((dev-alb-listener-arns))

cf-manifest-env-staging: &cf-manifest-env-staging
  environment_variables:
    FLASK_ENV: staging
    BROKER_USERNAME: ((broker-auth-username))
    BROKER_PASSWORD: ((broker-auth-password))
    SECRET_KEY: ((flask-secret-key))
    DATABASE_ENCRYPTION_KEY: ((staging-db-encryption-key))
    ROUTE53_ZONE_ID: ((staging-route53-zone-id))
    DNS_ROOT_DOMAIN: ((staging-dns-root-domain))
    DEFAULT_CLOUDFRONT_ORIGIN: ((staging-default-cloudfront-origin-domain-name))
    AWS_GOVCLOUD_REGION: ((staging-aws-govcloud-region))
    AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((staging-aws-govcloud-secret-access-key))
    AWS_GOVCLOUD_ACCESS_KEY_ID: ((staging-aws-govcloud-access-key-id))
    AWS_COMMERCIAL_REGION: ((staging-aws-commercial-region))
    AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((staging-aws-commercial-secret-access-key))
    AWS_COMMERCIAL_ACCESS_KEY_ID: ((staging-aws-commercial-access-key-id))
    ALB_LISTENER_ARNS: ((staging-alb-listener-arns))

cf-manifest-env-production: &cf-manifest-env-production
  environment_variables:
    FLASK_ENV: production
    BROKER_USERNAME: ((broker-auth-username))
    BROKER_PASSWORD: ((broker-auth-password))
    SECRET_KEY: ((flask-secret-key))
    DATABASE_ENCRYPTION_KEY: ((production-db-encryption-key))
    ROUTE53_ZONE_ID: ((production-route53-zone-id))
    DNS_ROOT_DOMAIN: ((production-dns-root-domain))
    DEFAULT_CLOUDFRONT_ORIGIN: ((production-default-cloudfront-origin-domain-name))
    AWS_GOVCLOUD_REGION: ((production-aws-govcloud-region))
    AWS_GOVCLOUD_SECRET_ACCESS_KEY: ((production-aws-govcloud-secret-access-key))
    AWS_GOVCLOUD_ACCESS_KEY_ID: ((production-aws-govcloud-access-key-id))
    AWS_COMMERCIAL_REGION: ((production-aws-commercial-region))
    AWS_COMMERCIAL_SECRET_ACCESS_KEY: ((production-aws-commercial-secret-access-key))
    AWS_COMMERCIAL_ACCESS_KEY_ID: ((production-aws-commercial-access-key-id))
    ALB_LISTENER_ARNS: ((production-alb-listener-arns))

acceptance-tests-params-staging-alb: &acceptance-tests-params-staging-alb
  PLAN_NAME: "domain"
  SERVICE_NAME: "external-domain"
  DNS_ROOT_DOMAIN: ((staging-dns-root-domain))
  HOSTED_ZONE_ID_0: ((staging-test-hosted-zone-id-2))
  TEST_DOMAIN_0: ((staging-test-domain-2))
  HOSTED_ZONE_ID_1: ((staging-test-hosted-zone-id-3))
  TEST_DOMAIN_1: ((staging-test-domain-3))
  AWS_ACCESS_KEY_ID: ((staging-test-user-aws-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((staging-test-user-aws-secret-access-key))
  AWS_REGION: ((staging-aws-commercial-region))

acceptance-tests-params-staging-cdn: &acceptance-tests-params-staging-cdn
  PLAN_NAME: "domain-with-cdn"
  SERVICE_NAME: "external-domain"
  DNS_ROOT_DOMAIN: ((staging-dns-root-domain))
  HOSTED_ZONE_ID_0: ((staging-test-hosted-zone-id-0))
  TEST_DOMAIN_0: ((staging-test-domain-0))
  HOSTED_ZONE_ID_1: ((staging-test-hosted-zone-id-1))
  TEST_DOMAIN_1: ((staging-test-domain-1))
  AWS_ACCESS_KEY_ID: ((staging-test-user-aws-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((staging-test-user-aws-secret-access-key))
  AWS_REGION: ((staging-aws-commercial-region))

acceptance-tests-params-production-cdn: &acceptance-tests-params-production-cdn
  PLAN_NAME: "domain-with-cdn"
  SERVICE_NAME: "external-domain"
  DNS_ROOT_DOMAIN: ((production-dns-root-domain))
  AWS_ACCESS_KEY_ID: ((production-test-user-aws-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((production-test-user-aws-secret-access-key))
  AWS_REGION: ((production-aws-commercial-region))
  HOSTED_ZONE_ID_0: ((production-test-hosted-zone-id-0))
  TEST_DOMAIN_0: ((production-test-domain-0))
  HOSTED_ZONE_ID_1: ((production-test-hosted-zone-id-1))
  TEST_DOMAIN_1: ((production-test-domain-1))

acceptance-tests-params-production-alb: &acceptance-tests-params-production-alb
  PLAN_NAME: "domain"
  SERVICE_NAME: "external-domain"
  DNS_ROOT_DOMAIN: ((production-dns-root-domain))
  AWS_ACCESS_KEY_ID: ((production-test-user-aws-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((production-test-user-aws-secret-access-key))
  AWS_REGION: ((production-aws-commercial-region))
  HOSTED_ZONE_ID_0: ((production-test-hosted-zone-id-2))
  TEST_DOMAIN_0: ((production-test-domain-2))
  HOSTED_ZONE_ID_1: ((production-test-hosted-zone-id-3))
  TEST_DOMAIN_1: ((production-test-domain-3))

############################
#  JOBS

jobs:

- name: reconfigure
  serial: true
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
  - get: secrets
    # Remember to manually trigger a new build if you upload a new version
    # of the credentials file.
    trigger: false
  - set_pipeline: ((name))
    file: src/ci/pipeline.yml
    var_files:
    - secrets/((name)).yml

- name: test
  plan:
  - get: src
    params: {depth: 1}
    trigger: true
    passed: [reconfigure]

  - put: dev-docker-image
    # We push this docker image _only_ so that we can use it in the next task
    # below.  :shrug: concourse.
    params:
      build: src
      dockerfile: src/docker/Dockerfile.dev
      tag_as_latest: true
      cache: true

  - task: test
    # Run the tests using the image pushed above.
    image: dev-docker-image
    config:
      platform: linux
      params:
        TMPDIR: /tmp
      run:
        path: /app/docker/tests

- name: dev
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [test]
    - get: pipeline-tasks
  - in_parallel:
    - task: create-postgres
      file: pipeline-tasks/ensure-misbehaved-service.yml
      params:
        <<: *cf-creds-dev
        <<: *create-postgres-service-params
    - task: create-redis
      file: pipeline-tasks/ensure-misbehaved-service.yml
      params:
        <<: *cf-creds-dev
        <<: *create-redis-service-params
  - task: stop-apps
    file: src/ci/stop-apps.yml
    params:
      <<: *cf-creds-dev
      APPLICATIONS: "((name)) ((name))-workers"
  - task: upgrade-schema
    file: src/ci/upgrade-schema.yml
    params:
      <<: *cf-creds-dev
      <<: *upgrade-schema-vars
  - in_parallel:
    - put: cf-dev
      params:
        path: src
        manifest: src/manifests/app.yml
        show_app_log: true
        <<: *cf-manifest-vars
        <<: *cf-manifest-env-dev
    - put: cf-dev
      params:
        path: src
        manifest: src/manifests/workers.yml
        show_app_log: true
        <<: *cf-manifest-vars
        <<: *cf-manifest-env-dev
  - task: register-broker
    file: pipeline-tasks/register-service-broker.yml
    params:
      <<: *cf-creds-dev
      <<: *broker-register-params

- name: staging
  serial_groups: [staging]
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [dev]
    - get: pipeline-tasks
  - in_parallel:
    - task: create-postgres
      file: pipeline-tasks/ensure-misbehaved-service.yml
      params:
        <<: *cf-creds-staging
        <<: *create-postgres-service-params
    - task: create-redis
      file: pipeline-tasks/ensure-misbehaved-service.yml
      params:
        <<: *cf-creds-staging
        <<: *create-redis-service-params
  - task: stop-apps
    file: src/ci/stop-apps.yml
    params:
      <<: *cf-creds-staging
      APPLICATIONS: "((name)) ((name))-workers"
  - task: upgrade-schema
    file: src/ci/upgrade-schema.yml
    params:
      <<: *cf-creds-staging
      <<: *upgrade-schema-vars
  - in_parallel:
    - put: cf-staging
      params:
        path: src
        manifest: src/manifests/app.yml
        show_app_log: true
        <<: *cf-manifest-vars
        <<: *cf-manifest-env-staging
    - put: cf-staging
      params:
        path: src
        manifest: src/manifests/workers.yml
        show_app_log: true
        <<: *cf-manifest-vars
        <<: *cf-manifest-env-staging
  - task: register-broker
    file: pipeline-tasks/register-service-broker.yml
    params:
      <<: *cf-creds-staging
      <<: *broker-register-params

- name: staging-acceptance-tests
  serial_groups: [staging]
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      passed: [staging]
    - get: cf-staging
      trigger: true
      passed: [staging]
    - get: dev-docker-image
    - get: test-timer
      trigger: true
  - in_parallel:
    - task: acceptance-cdn
      image: dev-docker-image
      timeout: 6h
      config:
        platform: linux
        params:
          <<: *cf-creds-staging
          <<: *acceptance-tests-params-staging-cdn
        run:
          path: /app/acceptance/run.sh
    - task: acceptance-alb
      image: dev-docker-image
      timeout: 6h
      config:
        platform: linux
        params:
          <<: *cf-creds-staging
          <<: *acceptance-tests-params-staging-alb
        run:
          path: /app/acceptance/run.sh

- name: production
  serial_groups: [production]
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      trigger: true
      passed: [staging-acceptance-tests]
    - get: pipeline-tasks
  - in_parallel:
    - task: create-postgres
      file: pipeline-tasks/ensure-misbehaved-service.yml
      params:
        <<: *cf-creds-production
        <<: *create-postgres-service-params
    - task: create-redis
      file: pipeline-tasks/ensure-misbehaved-service.yml
      params:
        <<: *cf-creds-production
        <<: *create-redis-service-params
  - task: stop-apps
    file: src/ci/stop-apps.yml
    params:
      <<: *cf-creds-production
      APPLICATIONS: "((name)) ((name))-workers"
  - task: upgrade-schema
    file: src/ci/upgrade-schema.yml
    params:
      <<: *cf-creds-production
      <<: *upgrade-schema-vars
  - in_parallel:
    - put: cf-production
      params:
        path: src
        manifest: src/manifests/app.yml
        show_app_log: true
        <<: *cf-manifest-vars
        <<: *cf-manifest-env-production
    - put: cf-production
      params:
        path: src
        manifest: src/manifests/workers.yml
        show_app_log: true
        <<: *cf-manifest-vars
        <<: *cf-manifest-env-production
  - task: register-broker
    file: pipeline-tasks/register-service-broker.yml
    params:
      <<: *cf-creds-production
      <<: *broker-register-params

- name: production-acceptance-tests
  serial_groups: [production]
  plan:
  - in_parallel:
    - get: src
      params: {depth: 1}
      passed: [production]
    - get: cf-production
      trigger: true
      passed: [production]
    - get: dev-docker-image
    - get: test-timer
      trigger: true
  - in_parallel:
    - task: acceptance-cdn
      image: dev-docker-image
      timeout: 6h
      config:
        platform: linux
        params:
          <<: *cf-creds-production
          <<: *acceptance-tests-params-production-cdn
        run:
          path: /app/acceptance/run.sh
    - task: acceptance-alb
      image: dev-docker-image
      timeout: 6h
      config:
        platform: linux
        params:
          <<: *cf-creds-production
          <<: *acceptance-tests-params-production-alb
        run:
          path: /app/acceptance/run.sh
############################
#  RESOURCES

resources:

- name: secrets
  type: s3-iam
  icon: cloud-lock
  source:
    region_name: ((concourse-varz-bucket-region))
    bucket: ((concourse-varz-bucket))
    versioned_file: ((name)).yml

- name: src
  type: git
  icon: github-circle
  check_every: 10s
  source:
    uri: https://github.com/cloud-gov/((name))
    branch: ((git-branch))

- name: dev-docker-image
  type: docker-image
  icon: docker
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-image-dev))

- name: cf-dev
  type: cf
  icon: cloud-upload
  source:
    api: ((dev-cf-api-url))
    username: ((dev-cf-username))
    password: ((dev-cf-password))
    organization: ((broker-organization))
    space: ((broker-space))

- name: cf-staging
  type: cf
  icon: cloud-upload
  source:
    api: ((staging-cf-api-url))
    username: ((staging-cf-username))
    password: ((staging-cf-password))
    organization: ((broker-organization))
    space: ((broker-space))

- name: cf-production
  type: cf
  icon: cloud-upload
  source:
    api: ((production-cf-api-url))
    username: ((production-cf-username))
    password: ((production-cf-password))
    organization: ((broker-organization))
    space: ((broker-space))

- name: pipeline-tasks
  type: git
  icon: github-circle
  source:
    uri: ((pipeline-tasks-git-url))
    branch: ((pipeline-tasks-git-branch))

- name: test-timer
  type: time
  source:
    start: 8:00 AM
    stop: 8:00 PM
    timezone: America/New_York
    days:
      - Monday
      - Tuesday
      - Wednesday
      - Thursday
      - Friday

############################
#  RESOURCE TYPES

resource_types:

- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
